//
//  SwiftMeta.swift
//  SwiftTwaceApp
//
//  Created by John Holdsworth on 20/04/2020.
//  Copyright © 2020 John Holdsworth. All rights reserved.
//
//  Repo: https://github.com/johnno1962/SwiftTrace
//  $Id: //depot/SwiftTrace/SwiftTrace/SwiftMeta.swift#61 $
//
//  Requires https://github.com/johnno1962/StringIndex.git
//
//  Assumptions made about Swift MetaData
//  =====================================
//

import Foundation

// Taken from stdlib, not public Swift3+
@_silgen_name("swift_demangle")
private
func _stdlib_demangleImpl(
    _ mangledName: UnsafePointer<CChar>?,
    mangledNameLength: UInt,
    outputBuffer: UnsafeMutablePointer<UInt8>?,
    outputBufferSize: UnsafeMutablePointer<UInt>?,
    flags: UInt32
    ) -> UnsafeMutablePointer<CChar>?

/**
 Shenaniggans to be able to decorate any type linked into an app.
 These functions have the SwiftMeta.FunctionTakingGenericValue
 signature from a C perspective if you can find the address.
 They need to be public at the top level when app is stripped.
 */

/// generic function to find the Optional type for a wrapped type
public func getOptionalType<Type>(value: Type, out: inout Any.Type?) {
    out = Optional<Type>.self
}

/// generic function to find the Array type for an element type
public func getArrayType<Type>(value: Type, out: inout Any.Type?) {
    out = Array<Type>.self
}

/// generic function to find the ArraySlice slice type for an element type
public func getArraySliceType<Type>(value: Type, out: inout Any.Type?) {
    out = ArraySlice<Type>.self
}

/// generic function to find the Dictionary with String key for an element type
public func getDictionaryType<Type>(value: Type, out: inout Any.Type?) {
    out = Dictionary<String, Type>.self
}

// generic function to find the Set type for a Hashable wrapped type
public func getSetType<Type: Hashable>(value: Type, out: inout Any.Type?) {
    out = Set<Type>.self
}

// generic function to find the Foundation.Measurement type for a Unit
@available(OSX 10.12, iOS 10.0, *)
public func getMeasurementType<Type: Unit>(value: Type, out: inout Any.Type?) {
    out = Foundation.Measurement<Type>.self
}

public class SwiftMeta {

    /// All types have this structure generated by the compiler
    /// from which you can extract the size and stride.
    struct ValueWitnessTable {
        let initializeBufferWithCopyOfBuffer: IMP, destroy: IMP,
            initializeWithCopy: IMP, assignWithCopy: IMP,
            initializeWithTake: IMP, assignWithTake: IMP,
            getEnumTagSinglePayload: IMP, storeEnumTagSinglePayload: IMP
        let size: size_t, stride: size_t
        let flags: uintptr_t
    }

    /**
     Get the size in bytes of a type
     */
    public class func sizeof(anyType: Any.Type) -> size_t {
        let metaData = unsafeBitCast(anyType,
            to: UnsafePointer<UnsafePointer<ValueWitnessTable>>.self)
        return metaData[-1].pointee.size
    }

    /**
     Get the stride in bytes of a type
     */
    public class func strideof(anyType: Any.Type) -> size_t {
        let metaData = unsafeBitCast(anyType,
            to: UnsafePointer<UnsafePointer<ValueWitnessTable>>.self)
        return metaData[-1].pointee.stride
    }

    /**
     The signature of a function taking a generic type and an inout pointer.
     The witnessTable is for when the type is constrained by a protocol.
     */
    public typealias FunctionTakingGenericValue = @convention(c) (
        _ valuePtr : UnsafeRawPointer?, _ outPtr: UnsafeMutableRawPointer,
        _ metaType: UnsafeRawPointer, _ witnessTable: UnsafeRawPointer?) -> ()

    /**
     This can be used to call a Swift function with a generic value
     argument when you have a pointer to the value and its type.
     See: https://www.youtube.com/watch?v=ctS8FzqcRug
     */
    public static func thunkToGeneric(funcPtr: FunctionTakingGenericValue,
        valuePtr: UnsafeRawPointer?, outPtr: UnsafeMutableRawPointer,
        type: Any.Type, witnessTable: UnsafeRawPointer? = nil) {
        funcPtr(valuePtr, outPtr, autoBitCast(type), witnessTable)
    }

    /**
     Definitions related to auto-tracability of types
     */
    static let RTLD_DEFAULT = UnsafeMutableRawPointer(bitPattern: -2)
    public static func mangle(_ name: String) -> String {
        return "\(name.utf8.count)\(name)"
    }

    /**
     Find pointer for function processing type as generic
     */
    public static func bindGeneric(name: String,
                                   owner: Any.Type = SwiftMeta.self,
                                   args: String = genericArgumentMangling)
                                   -> FunctionTakingGenericValue {
        let module = _typeName(owner).components(separatedBy: ".")[0]
        let symbol = "$s\(mangle(module))\(mangle(name))\(args)"
        guard let genericFunctionPtr = dlsym(RTLD_DEFAULT, symbol) else {
            fatalError("Could lot locate generic function for symbol \(symbol)")
        }
        return autoBitCast(genericFunctionPtr)
    }

    /**
     Generic function pointers that can be used to convert a type
     into the Optional/Array/Set/Dictionary for that type.
     */
    public static let genericArgument = "5value3outyx"
    public static let returnAnyType = "_ypXpSgztlF"
    public static let genericArgumentMangling = genericArgument+returnAnyType

    static var getOptionalTypeFptr = bindGeneric(name: "getOptionalType")
    static var getSetTypeFptr = bindGeneric(name: "getSetType",
                                        args: genericArgument+"_ypXpSgztSHRzlF")

    /// Handled compund types
    public static var wrapperHandlers = [
        "Swift.Optional<": getOptionalTypeFptr,
        "Swift.Array<": bindGeneric(name: "getArrayType"),
        "Swift.ArraySlice<": bindGeneric(name: "getArraySliceType"),
        "Swift.Dictionary<Swift.String, ": bindGeneric(name: "getDictionaryType"),
        "Foundation.Measurement<": bindGeneric(name: "getMeasurementType",
                                args: genericArgument+"_ypXpSgztSo6NSUnitCRbzlF"),
    ]

    public static var nameAbbreviations = [
        "Swift": "s"
    ]

    public static var typeLookupCache: [String: Any.Type?] = [
        // These types have non-standard manglings
        "Swift.String": String.self,
        "Swift.Double": Double.self,
        "Swift.Float": Float.self,
//        "Any": Any.self,

        // Has private enum property containg a Locale
        "Fruta.ContentView" : nil,
        // Snother problem Foundation inside enum
        "Kingfisher.ExpirationExtending": nil,
    ]
    static var typeLookupCacheLock = OS_SPINLOCK_INIT

    /**
     You need to use this value ro prevent type lookup as assigning nil will just delete the key..
     */
    public static let PreventLookup: Any.Type? = nil

    /**
     Best effort recovery of type from a qualified name
     */
    public static func lookupType(named: String,
                           exclude: NSRegularExpression? = nil) -> Any.Type? {
        if exclude?.matches(named) == true {
            return nil
        }
        OSSpinLockLock(&typeLookupCacheLock)
        defer { OSSpinLockUnlock(&typeLookupCacheLock) }
        return lockedType(named: named, exclude: exclude)
    }

    static func lockedType(named: String,
                           exclude: NSRegularExpression? = nil) -> Any.Type? {
        if let type = typeLookupCache[named] {
            return type
        }

        var out: Any.Type?
        for (prefix, handler) in wrapperHandlers where named.hasPrefix(prefix) {
            if let wrapped = named[safe: .start+prefix.count ..< .end-1],
                let wrappedType = SwiftMeta.lockedType(named: wrapped,
                                                      exclude: exclude) {
                thunkToGeneric(funcPtr: handler, valuePtr: nil,
                               outPtr: &out, type: wrappedType)
            }
            break
        }

        if named.hasSuffix("..."),
            let element = named[safe: ..<(.end-3)] {
            out = lockedType(named: "Swift.Array<\(element)>")
        } else if out == nil && named.hasPrefix("Swift.Set<"),
            let element = named[safe: .start+10 ..< .end-1],
            let elementType = SwiftMeta.lockedType(named: element,
                                                   exclude: exclude),
            let hashableWitness = getHashableWitnessTable(for: elementType) {
            thunkToGeneric(funcPtr: getSetTypeFptr, valuePtr: nil,
                           outPtr: &out, type: elementType,
                           witnessTable: hashableWitness)
        } else if out == nil {
            var mangled = ""
            var first = true
            for name in named.components(separatedBy: ".") {
                mangled += nameAbbreviations[name] ?? mangle(name)
                out = nil
                if first {
                    first = false
                    continue
                }
                if let type = _typeByName(mangled+"C") {
                    mangled += "C" // class type
                    out = type
                } else if let type = _typeByName(mangled+"V") {
                    mangled += "V" // value type
                    out = type
                } else if let type = _typeByName(mangled+"O") {
                    mangled += "O" // enum type?
                    out = type
                } else {
                    break
                }
            }
        }
        typeLookupCache[named] = out
        return out
    }

    /**
     Take the symbol name for the metaType address and remove the "N" suffix
     */
    public static func mangledName(for type: Any.Type) -> String? {
        var info = Dl_info()
        if dladdr(autoBitCast(type), &info) != 0,
            let metaTypeSymbol = info.dli_sname {
            return String(cString: metaTypeSymbol)[safe: ..<(.end-1)]
        }
        return nil
    }

    /**
     Find the witness table for the conformance of elementType to Hashable
     */
    static func getHashableWitnessTable(for elementType: Any.Type)
        -> UnsafeRawPointer? {
        var hashableWitnessTable: UnsafeRawPointer?
        if let mangledName = mangledName(for: elementType) {
            if let theEasyWay = dlsym(RTLD_DEFAULT, mangledName+"SHsWP") {
                hashableWitnessTable = UnsafeRawPointer(theEasyWay)
            } else {
                let witnessSuffix = "ACSHAAWl"
                (mangledName + witnessSuffix).withCString { getWitnessSymbol in
                    typealias GetWitness = @convention(c) () -> UnsafeRawPointer
                    let bundlePath = Bundle.main.executablePath!
                    findSwiftSymbols(bundlePath, witnessSuffix) {
                        (address, symbol, _, _) in
                        if strcmp(symbol, getWitnessSymbol) == 0,
                            let witnessFptr: GetWitness = autoBitCast(address) {
                            hashableWitnessTable = witnessFptr()
                        }
                    }
                }
            }
        }
        return hashableWitnessTable
    }

    /**
     Information about a field of a struct or class
     */
    public struct FieldInfo {
        let name: String
        let type: Any.Type
        let offset: size_t
    }

    /**
     Get approximate nformation about the fields of a type
     */
    public static func fieldInfo(forAnyType: Any.Type) -> [FieldInfo]? {
        _ = structsPassedByReference
        return approximateFieldInfoByTypeName[_typeName(forAnyType)]
    }

    static var approximateFieldInfoByTypeName = [String: [FieldInfo]]()

    public static var structsPassedByReference: Set<UnsafeRawPointer> = {
        var problemTypes = Set<UnsafeRawPointer>()
        func passedByReference(_ type: Any.Type) {
            problemTypes.insert(autoBitCast(type))
        }
        for var type: Any.Type in [
            URL.self, UUID.self, Date.self, IndexPath.self, IndexSet.self] {
            passedByReference(type)
            thunkToGeneric(funcPtr: getOptionalTypeFptr,
                           valuePtr: nil, outPtr: &type, type: type)
            passedByReference(type)
        }

        appBundleImages { bundlePath, _ in
            process(bundlePath: bundlePath, problemTypes: &problemTypes)
        }

        passedByReference(Any.self)
        passedByReference(Any?.self)
//        print(problemTypes.map {unsafeBitCast($0, to: Any.Type.self)}, approximateFieldInfoByTypeName)
        return problemTypes
    }()


    /**
     Structs that have only fields that conform to .SwiftTraceFloatArg
     */
    static var structsAllFloats = Set<UnsafeRawPointer>()

    /**
     Ferforms a one time scan of all property getters at a bundlePath to
     look out for structs that are or contain bridged(?) values such as URL
     or UUID and are passed by reference by the compiler for some reason.
     */
    public static func process(bundlePath: UnsafePointer<Int8>,
                   problemTypes: UnsafeMutablePointer<Set<UnsafeRawPointer>>) {
        func passedByReference(_ type: Any.Type) {
            problemTypes.pointee.insert(autoBitCast(type))
        }
        func debug(_ str: String) {
//            print(str)
        }

        var offset = 0
        var currentType = ""
        var wasFloatType = false

        findSwiftSymbols(bundlePath, "g") { (_, symbol, _, _) in
//                print(String(cString: symbol))
            if let demangled = SwiftMeta.demangle(symbol: symbol) {
//                    print(demangled)
                if let typeStart = demangled.index(of: .first(of: ":")+2),
                   let nameEnd = demangled.index(of: typeStart + .last(of: ".")),
                   let typeEnd = demangled.index(of: nameEnd + .last(of: ".")),
                   let typeName = demangled[safe: ..<(typeEnd+0)],
                   let fieldName = demangled[safe: typeEnd+1 ..< nameEnd],
                   let fieldTypeName = demangled[safe: (typeStart+0)...],
                   let type = SwiftMeta.lookupType(named: typeName) {
                    debug("\(typeName).\(fieldName): \(fieldTypeName)")
                    let typeIsClass = type is AnyClass
                    let symend = symbol+strlen(symbol)
                    if strcmp(symend-3, "Ovg") == 0 || // enum
                        strcmp(symend-5, "OSgvg") == 0, !typeIsClass {
                        debug("\(typeName) enum prop \(fieldTypeName)")
                        typeLookupCache[typeName] = PreventLookup
                        return
                    }

                    if let fieldType = SwiftMeta.lookupType(named: fieldTypeName) {
                        let isFloatField = fieldType is SwiftTraceFloatArg.Type
                        if currentType != typeName {
                            currentType = typeName
                            wasFloatType = isFloatField
                            approximateFieldInfoByTypeName[typeName] = [FieldInfo]()
                            offset = type is AnyClass ? 8 * 3 : 0
                            if isFloatField && !typeIsClass {
                                structsAllFloats.insert(autoBitCast(type))
                            }
                        }

                        let strideMinus1 = strideof(anyType: fieldType) - 1
                        offset = (offset + strideMinus1) & ~strideMinus1
                        approximateFieldInfoByTypeName[typeName]?.append(
                            FieldInfo(name: fieldName, type: fieldType, offset: offset))
                        offset += sizeof(anyType: fieldType)

                        if !isFloatField {
                            structsAllFloats.remove(autoBitCast(type))
                        }

                        if typeIsClass {
                            return
                        }

                        if isFloatField != wasFloatType &&
                            !(type is SwiftTraceFloatArg.Type) {
                            debug("\(typeName) Mixed properties")
                            typeLookupCache[typeName] = PreventLookup
                        }

                        if problemTypes.pointee.contains(autoBitCast(fieldType)) {
                            debug("\(typeName) Reference prop \(fieldTypeName)")
//                            typeLookupCache[typeName] = PreventLookup
                            passedByReference(type)
                        } else if let optional = fieldType as? OptionalTyping.Type,
                            problemTypes.pointee.contains(autoBitCast(optional.wrappedType)) {
                            debug("\(typeName) Reference optional prop \(fieldTypeName)")
                            passedByReference(type)
                            passedByReference(fieldType)
                        } else if fieldTypeName.hasPrefix("Foundation.Measurement<") {
                            debug("\(typeName) Measurement prop \(fieldTypeName)")
                            passedByReference(type)
                            passedByReference(fieldType)
                        }
                    }
                }
            }
        }
    }

    /** pointer to a function implementing a Swift method */
    public typealias SIMP = @convention(c) () -> Void

    /**
     Value that crops up as a ClassSize since 5.2 runtime
     */
    static let invalidClassSize = 0x50AF17B0

    /**
     Layout of a class instance. Needs to be kept in sync with ~swift/include/swift/Runtime/Metadata.h
     */
    public struct TargetClassMetadata {

        let MetaClass: uintptr_t = 0, SuperClass: uintptr_t = 0
        let CacheData1: uintptr_t = 0, CacheData2: uintptr_t = 0

        public let Data: uintptr_t = 0

        /// Swift-specific class flags.
        public let Flags: UInt32 = 0

        /// The address point of instances of this type.
        public let InstanceAddressPoint: UInt32 = 0

        /// The required size of instances of this type.
        /// 'InstanceAddressPoint' bytes go before the address point;
        /// 'InstanceSize - InstanceAddressPoint' bytes go after it.
        public let InstanceSize: UInt32 = 0

        /// The alignment mask of the address point of instances of this type.
        public let InstanceAlignMask: UInt16 = 0

        /// Reserved for runtime use.
        public let Reserved: UInt16 = 0

        /// The total size of the class object, including prefix and suffix
        /// extents.
        public let ClassSize: UInt32 = 0

        /// The offset of the address point within the class object.
        public let ClassAddressPoint: UInt32 = 0

        /// An out-of-line Swift-specific description of the type, or null
        /// if this is an artificial subclass.  We currently provide no
        /// supported mechanism for making a non-artificial subclass
        /// dynamically.
        public let Description: uintptr_t = 0

        /// A function for destroying instance variables, used to clean up
        /// after an early return from a constructor.
        public var IVarDestroyer: SIMP? = nil

        // After this come the class members, laid out as follows:
        //   - class members for the superclass (recursively)
        //   - metadata reference for the parent, if applicable
        //   - generic parameters for this class
        //   - class variables (if we choose to support these)
        //   - "tabulated" virtual methods

    }

    /**
     Convert a executable symbol name "mangled" according to Swift's
     conventions into a human readable Swift language form
     */
    @objc open class func demangle(symbol: UnsafePointer<Int8>) -> String? {
        if let demangledNamePtr = _stdlib_demangleImpl(
            symbol, mangledNameLength: UInt(strlen(symbol)),
            outputBuffer: nil, outputBufferSize: nil, flags: 0) {
            let demangledName = String(cString: demangledNamePtr)
            free(demangledNamePtr)
            return demangledName
        }
        return nil
    }
}

protocol OptionalTyping {
    static var wrappedType: Any.Type { get }
    static func describe(optionalPtr: UnsafeRawPointer, out: inout String)
}
extension Optional: OptionalTyping {
    static var wrappedType: Any.Type { return Wrapped.self }
    static func describe(optionalPtr: UnsafeRawPointer, out: inout String) {
        if var value = optionalPtr.load(as: Wrapped?.self) {
            SwiftTrace.Decorated.describe(&value, type: Wrapped.self, out: &out)
        } else {
            out += "nil"
        }
    }
}

/**
 Convenience extension to trap regex errors and report them
 */
extension NSRegularExpression {

    convenience init(regexp: String) {
        do {
            try self.init(pattern: regexp)
        }
        catch let error as NSError {
            fatalError("Invalid regexp: \(regexp): \(error.localizedDescription)")
        }
    }

    func matches(_ string: String) -> Bool {
        return rangeOfFirstMatch(in: string,
            range: NSRange(string.startIndex ..< string.endIndex,
                           in: string)).location != NSNotFound
    }
}
